### ISSUE TITLE
Database cleanup

### ISSUE THREAD

**Issue by skest3qc** [bgelens/DSCPullServerAdmin#1]
Hi,
first thanks for this great project. 
Since the database Devices.edb is growing and growing it would be nice if we could clean up StatusReports table. A switch how much days back we would like to have would be nice.

Thanks

**Comment by bgelens** [comment]
You actually mean clean out the rows from the table or just output you get from the Get Cmdlet?

**Comment by skest3qc** [comment]
Yes i mean to remove rows from the table

**Comment by bgelens** [comment]
I'll see if I can create a Remove-DSCPullServerAdminReport Cmdlet to do this and have the filtering on dates in the Get Cmdlet based on parameter input. Would this be helpful?

```powershell
Get-DSCPullServerAdminReport -FromDate 'somedate' -ToDate 'somedate' |
    Remove-DSCPullServerAdminReport -Confirm:$false
```

**Comment by skest3qc** [comment]
This works for me:
`using System.Collections.Generic;
using System.Management.Automation;
using Microsoft.Isam.Esent.Interop;
using System;
using DSCPullServerAdmin.src.Models;
using System.Web.Script.Serialization;


namespace DSCPullServerAdmin.src.CmdLets
{
    [Cmdlet(VerbsCommon.Remove, "DSCPullServerAdminReport")]
    [OutputType(typeof(StatusReport))]
    public class RemoveDSCPullServerAdminReport : BaseCmdlet
    {
        [Parameter(ParameterSetName = "TillDate")]
        [Alias("Date")]
        [ValidateNotNullOrEmpty()]
        public DateTime TillDate;

        public override string tableName
        {
            get
            {
                return "StatusReport";
            }
        }

        JavaScriptSerializer Serializer = new JavaScriptSerializer();

        protected override void ProcessRecord()
        {
            Api.MoveBeforeFirst(sesid, tableid);
            while (Api.TryMoveNext(sesid, tableid))
            {
                IDictionary<string, JET_COLUMNID> columnDictionary = Api.GetColumnDictionary(sesid, tableid);
                if (TillDate != null)
                {
                    DateTime StartTime = (DateTime)Api.RetrieveColumnAsDateTime(sesid, tableid, columnDictionary["StartTime"]);
                    if (StartTime > TillDate)
                    {
                        continue;
                    }
                }
                StatusReport report = new StatusReport();
                report.StartTime = (DateTime)Api.RetrieveColumnAsDateTime(sesid, tableid, columnDictionary["StartTime"]);
                report.EndTime = (DateTime)Api.RetrieveColumnAsDateTime(sesid, tableid, columnDictionary["EndTime"]);
                report.LastModifiedTime = (DateTime)Api.RetrieveColumnAsDateTime(sesid, tableid, columnDictionary["LastModifiedTime"]);
                report.JobId = (Guid)Api.RetrieveColumnAsGuid(sesid, tableid, columnDictionary["JobId"]);
                report.Id = (Guid)Api.RetrieveColumnAsGuid(sesid, tableid, columnDictionary["Id"]);
                report.OperationType = Api.RetrieveColumnAsString(sesid, tableid, columnDictionary["OperationType"]);
                report.RefreshMode = Api.RetrieveColumnAsString(sesid, tableid, columnDictionary["RefreshMode"]);
                report.Status = Api.RetrieveColumnAsString(sesid, tableid, columnDictionary["Status"]);
                report.LCMVersion = Api.RetrieveColumnAsString(sesid, tableid, columnDictionary["LCMVersion"]);
                report.ReportFormatVersion = Api.RetrieveColumnAsString(sesid, tableid, columnDictionary["ReportFormatVersion"]);
                report.ConfigurationVersion = Api.RetrieveColumnAsString(sesid, tableid, columnDictionary["ConfigurationVersion"]);
                report.NodeName = Api.RetrieveColumnAsString(sesid, tableid, columnDictionary["NodeName"]);
                report.IPAddress = Api.RetrieveColumnAsString(sesid, tableid, columnDictionary["IPAddress"]).Split(',');
                report.RebootRequested = bool.Parse(Api.RetrieveColumnAsString(sesid, tableid, columnDictionary["RebootRequested"]));
                report.Errors = (List<string>)Api.DeserializeObjectFromColumn(sesid, tableid, columnDictionary["Errors"]);
                report.StatusData = (List<string>)Api.DeserializeObjectFromColumn(sesid, tableid, columnDictionary["StatusData"]);
                //report.AdditionalData = Serializer.Deserialize<List<PropertyBag>>(Api.RetrieveColumnAsString(sesid, tableid, columnDictionary["AdditionalData"]));

                WriteObject("Removing DataRow");
                WriteObject(report);
                Api.JetDelete(sesid, tableid);
            }
        }
    }
}
`

**Comment by bgelens** [comment]
Hi @skest3qc I created a new release [0.0.0.5](https://github.com/bgelens/DSCPullServerAdmin/releases/tag/0.0.0.5)
This contains a Remove cmdlet for Reports. You can use it in multiple ways.
```powershell
Mount-DSCPullServerAdminDatabase -ESEPath '.\Devices.edb'
Get-DSCPullServerAdminRegistration
#whatif remove output from Get cmdlet
Get-DSCPullServerAdminReport | Remove-DSCPullServerAdminReport -WhatIf
#confirm impact on ToStartTime
Remove-DSCPullServerAdminReport -ToStartTime ([datetime]"01-29-2017")
#suppress confirm
Remove-DSCPullServerAdminReport -ToStartTime ([datetime]"01-29-2017") -FromStartTime ([datetime]"01-28-2017") -Confirm:$false
Dismount-DSCPullServerAdminDataBase
```
Let me know if this works for you.

Thanks, Ben

**Comment by skest3qc** [comment]
Hi Ben,
thanks for the update. It works great.
I have found one small problem (see screenshot)
![dsc](https://cloud.githubusercontent.com/assets/8022790/23198935/19840970-f8cb-11e6-9eb3-91023182ae26.png)

**Comment by bgelens** [comment]
Thanks for the feedback. I'll look into it

**Comment by Zuldan** [comment]
Wow I had no idea this module exists. Thank you @bgelens and @skest3qc. Massive issues with ESENT speed. I'm currently deleting the entire DB every 24 hours. @bgelens your module could be a life saver. https://github.com/PowerShell/xPSDesiredStateConfiguration/issues/296

**Comment by bgelens** [comment]
Thanks @Zuldan! Great people were missing something like this as much as I did :-)
Please note, this is all very early so you might want to copy your db before running the cmdlets against it.
I'm still figuring out how this JET thing works.

**Comment by ghost** [comment]
Thank you for this, it looks like it's going to be very helpful to everyone. 

Just a question regarding performance. 

~80GB database, ~400 agents, been around for a month or so. 

Any idea how long you would expect this command to take?

`Get-DSCPullServerAdminReport | Remove-DSCPullServerAdminReport -confirm:$false`

Been running it for around 24 hours, not got any feedback from it yet. Disk read (database is on a dedicated drive) is averaging 12MB/sec, powershell is consuming 4.4GB memory, and CPU is sitting just under 40% (2 vCPU, 2.20Ghz) on average...

**Comment by bgelens** [comment]
@allywilson1 I really don't know....  Guessing this could all be implemented in a much more efficient manner but I'm not at all an expert on JET unfortunately.

Hope you have a backup in case it doesn't work out as expected

**Comment by allywilson** [comment]
@bgelens Nah, don't worry about the backup. We were at the point of wiping it out as we couldn't reduce the size, until we found this issue (and subsequent feature you've made!). I've let it continue running. If I get fed up and wipe it out, or, if it succeeds before my patience runs out I'll let you know!

**Comment by allywilson** [comment]
@bgelens You know, as I typed the above, I checked the disk stats. I seen it [writing](http://imgur.com/a/DAnfg) to the EDB file (never above 1024 Bytes/Sec mind), and thought my wait was over, but it only lasted for a few seconds.

Could it be the case the Get | Remove is looping for every Remove? So, kinda like reading in the entire massive 80GB DB, then performing a single remove, then reading it all in again?

**Comment by bgelens** [comment]
@allywilson It will search through the database until the matching record is found. It's a nosql database so unfortunately you cannot just say, delete record 10 or something. Maybe it's faster for you if you wouldn't use the pipeline but use the parameter **FromStartTime** on the Remove cmdlet directly.

So ```Remove-DSCPullServerAdminReport -FromStartTime ([datetime]"1/1/2017")```

**Comment by allywilson** [comment]
Nice one! This command is looking a lot better...

`Remove-DSCPullServerAdminReport -FromStartTime (Get-Date).AddDays(-7) -ToStartTime (Get-Date) -confirm:$false`

Disk write activity is waaaay up. I'll report back.

EDIT: Reporting back after a few minutes: Some stats [included.](http://imgur.com/a/IfNHw). I'll keep an eye on it, and report back on dates/times if I can. 

EDIT2: The above 7 day deletion took 40 minutes (only clocked the finish by seeing the powershell window move to the next line, the EDB modification on NTFS has stayed the same). Trying a -30day to -7 day deletion now, don't think I'll see it complete this time/or in NTFS.

**Comment by ghost** [comment]
So, after removing all reports (did it in stages, 7 days, then 30 days, then 90 days, then 150 days)...I discovered I had 390,793 dated "12/30/1899 12:00:00 AM". So I removed all of them too.

Dismounted the EDB, but noticed the size did not shrink.

So, I did a defrag using esentutl:
`esentutl /d Devices.edb`

Took 333.63 seconds to shrink from 78.1GB to...1,032KB.

Rebooted, and it's working.

Thanks again!

**Comment by bgelens** [comment]
@allywilson1 Thanks for reporting this! Great it's working 👍

**Comment by raandree** [comment]
Not really about what you are discussing here but if reporting is important to you, SQL Server gives you a much better platform: https://blogs.technet.microsoft.com/fieldcoding/2017/05/11/using-sql-server-2016-for-a-dsc-pull-server/.

We have identified some issues with the MDB linked tables forwarding data to SQL if you have large reports in the StatusData table. After having reporting this to the Dsc Dev Team, they committed to release a new version of the pull server DLL with native SQL Server support. The database design and the queries I have referenced in the article mentioned above will change only very slightly.

**Comment by bgelens** [comment]
Great news @raandree! i'm sure everybody will move off mdb, edb once there is an official supported sql implementation 😄

**Comment by Zuldan** [comment]
@raandree this is fantastic news. You've made a lot of people very happy. Can we get a rough estimate for release. Within 6 months or 12 months?

**Comment by rpinxten** [comment]
Looks like the native SQL support for pull servers is here (https://www.powershellgallery.com/packages/xpsdesiredstateconfiguration/8.1.0.0)

**Comment by bgelens** [comment]
@rpinxten I did demo the SQL implementation at PSConfEU. Also dockerized the pull server. If you are interested, a video on the [PSConfEU YouTube](https://www.youtube.com/channel/UCxgrI58XiKnDDByjhRJs5fg) should be made available any week now. For materials see the [PSConfEU GitHub repo](https://github.com/psconfeu/2018/tree/master/Ben%20Gelens/The%20Dsc%20Pull%20Server%20is%20dead)

**Comment by bgelens** [comment]
Closing this issue. Currently all modification functions for edb have been dropped because of module redesign targeting SQL server as primary platform and offering ability to migrate edb data to sql.
If people still want edb options for remove, update, delete and new, please log a new issue
