### ISSUE TITLE
Instance Name already in use

### ISSUE THREAD

**Issue by skest3qc** [bgelens/DSCPullServerAdmin#2]
Running
`Get-DSCPullServerAdminReport -ESEPath 'C:\Program Files\WindowsPowerShell\DscService\Devices.edb' | select -Last 1`
once works. When i run the same code a second time i get the following message:
`Get-DSCPullServerAdminReport : Instance Name already in use
At line:1 char:1
+ Get-DSCPullServerAdminReport -ESEPath 'C:\Program Files\WindowsPowerS ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-DSCPullServerAdminReport], EsentInstanceNameInUseException
    + FullyQualifiedErrorId : Microsoft.Isam.Esent.Interop.EsentInstanceNameInUseException,DSCPullServerAdmin.src.CmdLets.GetDSCPullServerAdminReport`

This only happens if you start the cmdlet and break it while it is running (CTRL+C)

Env: Windows Server 2016
PS: 5.1.14393.693

**Comment by bgelens** [comment]
Thanks for reporting @skest3qc! I've noticed this myself as well. Seems Select-Object -First x throws a StopUpstreamCommandsException which I didn't account for. This prevents endprocessing or stopprocessing from running. I'll work on a fix.
