### ISSUE TITLE
New-DSCPullServerAdminConnection error when passing credential

### ISSUE THREAD

**Issue by mmcelreath** [bgelens/DSCPullServerAdmin#28]
When I try to pass a credential to New-DSCPullServerAdminConnection, I get the following error:

PS C:\> New-DSCPullServerAdminConnection -SQLServer SERVERNAME-Database DSC -Credential (Get-Credential)

cmdlet Get-Credential at command pipeline position 1
Supply values for the following parameters:
Credential
Invoke-DSCPullServerSQLCommand : Exception calling "Open" with "0" argument(s): "Login failed for user 'CORP\mcelreathm'."
At C:\Users\mcelreathm\Documents\WindowsPowerShell\Modules\DSCPullServerAdmin\0.1.5\DSCPullServerAdmin.psm1:1081 char:19
+ ... estResult = Invoke-DSCPullServerSQLCommand -Connection $testConnectio ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], MethodInvocationException
    + FullyQualifiedErrorId : SqlException,Invoke-DSCPullServerSQLCommand

I'm using an account that is a sysadmin on the SQL server which is also the account I'm logged in as. If I omit the -Credential parameter, it works fine.

PS C:\> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.15063.1292
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.15063.1292
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

**Comment by bgelens** [comment]
I think this is expected. Passing username and password is afaik only supported for SQL logins. With Windows authentication you need to be logged on using such credential hence not specifying credential works in your case.

**Comment by mmcelreath** [comment]
Oh ok. I see now. I wonder if there's a way to pass a windows cred to the SQL connection. I sometimes won't have access to certain SQL servers with the account I'm logged in as.

**Comment by bgelens** [comment]
You could spin up PowerShell using runas with an account that has access or use Invoke-Command -Credential $cred or something similar.

Closing the issue as this is not something I can build support for.
