### ISSUE TITLE
Default EDB File Path parameter

### ISSUE THREAD

**Issue by skest3qc** [bgelens/DSCPullServerAdmin#3]
Hi,
it would be nice if Paramter of ESEPath has a default value like 
"C:\Program Files\WindowsPowerShell\DscService\Devices.edb"

Thanks

**Comment by bgelens** [comment]
Thanks for the suggestion!

This is IMO not exactly **the** default path. Just the one used in the examples on how to configure the pull server. In my case, I got multiple pull server instances on a single box having multiple different database paths.

Maybe later I'll implement some additional Cmdlets enumerating pull servers on the box and then you could use this as input for the database Cmdlets. But for now I'm leaving this as is.

You could add the parameter value to your $PSDefaultParameterValues so you won't have to fill it in every time.

```powershell
$PSDefaultParameterValues.Add(
    "*-DSCPullServerAdmin*:ESEPath",
    "C:\Program Files\WindowsPowerShell\DscService\Devices.edb"
)

Get-DSCPullServerAdminReport
```
