### ISSUE TITLE
Provide ability to move EDB content to SQL DB

### ISSUE THREAD

**Issue by bgelens** [bgelens/DSCPullServerAdmin#5]
Now we have SQL support in Server 1803 (SAC) / 2019 (LTSC), it would be nice if we could get the content out of the EDB and insert it directly in the SQL Database to preserve existing node registrations and reporting data.

Right now my thinking is to have the ability to either create a new SQL DB from scratch or be able to connect up with an existing one.

* [x] Cmdlet/Function to create a new DB
* [x] Cmdlet/Function to connect with existing DB (created by either the Pull Server itself or by using the previously mentioned Cmdlet/Function)
* [x] Cmdlet/Function to convert EDB data to SQL INSERT Statements and execute on DB if not exists

**Comment by rdbartram** [comment]
perhaps its worth depending on the sqlserver module. There are two very easy commands read-sqltabledata and write-sqltabledata. Saves use reinventing the wheel.

IMO this is a one time thing, so a simple like below should be sufficient

``
Import-DSCPullServerData -edbfile $file -sqlserver $server -sqlinstance $instance
``

**Comment by rdbartram** [comment]
I can start working on some of the helper functions to split this feature into multiple PRs. Do you want to create a new branch to separate the incomplete version from master?

**Comment by bgelens** [comment]
master is pretty much alpha so I'm fine taking PRs to this branch. Thanks for helping out @rdbartram!

FYI, I started working in [EDBToSQL](https://github.com/bgelens/DSCPullServerAdmin/tree/EDBToSQL) branch

**Comment by bgelens** [comment]
Version 0.1.0 is now released implementing all envisioned features. 🎉
